down_sample:
  voxel_size: 0.01 # Number or null

filter_by_radius:
  max_radius: 55 #100
  min_radius: 1  #0.5 para no encontrarse con el robot

filter_by_height:
  min_height: -2
  max_height: 1.3

filter_ground_plane:
  radius_normals: 3
  maximum_neighbors: 300 #200

normals:
  maximum_neighbors: 300 #50
  radius_normals: 3 #0.5

icp:
  # find the closest points within this distance
  distance_threshold: 7.0 #5